# https://pub.dev/packages/pedantic_mono
include: package:pedantic_mono/analysis_options.yaml

analyzer:
  exclude:
    - "lib/firebase_options.dart"
    - "lib/**/*.g.dart"
    - "lib/**/*.freezed.dart"
  errors:
    flutter_style_todos: ignore

plugins:
  riverpod_lint: ^3.1.3

linter:
  rules:
    lines_longer_than_80_chars: false
