targets:
  $default:
    builders:
      json_serializable:
        options:
          field_rename: snake
        generate_for:
          include:
            - lib/src/data/**/*.dart
      freezed:
        generate_for:
          include:
            - lib/src/data/**/*.dart
