name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.4'
        channel: 'stable'
        cache: true
    
    - name: Verify Flutter installation
      run: |
        flutter --version
        flutter doctor -v
    
    - name: Get dependencies
      run: flutter pub get
    
    - name: Generate required files
      run: |
        # Create a mock firebase_options.dart for CI if it doesn't exist
        if [ ! -f "lib/firebase_options.dart" ]; then
          echo "Creating mock firebase_options.dart for CI..."
          mkdir -p lib
          cp .github/workflows/firebase_options_mock.dart lib/firebase_options.dart
        fi
        
        # Verify dependencies are installed
        echo "Installing dependencies..."
        flutter pub get
        
        # Generate build_runner files with better error handling
        echo "Generating build_runner files..."
        flutter pub run build_runner build --delete-conflicting-outputs || {
          echo "build_runner failed, trying with verbose output..."
          flutter pub run build_runner build --delete-conflicting-outputs --verbose
        }
        
        # Setup sqflite for web
        echo "Setting up sqflite for web..."
        dart run sqflite_common_ffi_web:setup || echo "sqflite_common_ffi_web setup failed, continuing..."
    
    - name: Analyze project source
      run: flutter analyze --fatal-infos
    
    - name: Run custom lint
      run: dart run custom_lint
    
    - name: Run tests
      run: |
        echo "Running Flutter tests..."
        flutter test --coverage || {
          echo "Tests failed, running with verbose output..."
          flutter test --verbose
        }
    
    - name: Check build for Web
      run: flutter build web --target=lib/main.dart --no-tree-shake-icons