name: Security Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run security checks weekly on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'

jobs:
  security:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.1'
        channel: 'stable'
        cache: true
    
    - name: Get dependencies
      run: flutter pub get
    
    - name: Check for vulnerabilities
      run: |
        # Check for known vulnerabilities in dependencies
        flutter pub deps --json > deps.json
        
        # This is a basic check - in production you might want to use more sophisticated tools
        if grep -i "vulnerability\|security\|exploit" pubspec.lock; then
          echo "Potential security concerns found in dependencies"
          echo "Please review the flagged dependencies"
        fi
        
        echo "Basic security check completed"
        rm -f deps.json